Chat-Format: "{rank}{faction}{player-name} > {msg}"
Faction-Format: "[{value}]"
Rank-Format: "[{value}]"
Join-Message: "&eWelcome to the server &7@&2{player}"
Leave-Message: "{player} left"

mysql-host: "truelinux.cf"
mysql-pass: "3X0T~l1p8mJ*"
mysql-db: "truelinu_mcpe"
mysql-user: "truelinu_admin"
mysql-port: 3306

server-data:
  file: "cyber_core_data.db"
  table: "mcpe"
  data:
    uuid:
      type: "varchar(50)"
    faction_id:
      type: "varchar(32)"
    money:
      type: "int(12)"
    kills:
      type: "int(9)"
    deaths:
      type: "int(9)"
    banned:
      type: "int(1)"