name: CyberCore
main: net.yungtechboy1.CyberCore.CyberCoreMain
version: "1.0.0"
api: ["1.0.9"]
load: POSTWORLD
author: Yungtechboy1
description: Core Plugin from Yungtech
permissions:
  CyberTech.CyberCore:
    description: "CyberCore Perms"
    children:
      CyberTech.CyberCore.op:
        default: op
      CyberTech.CyberCore.player:
        default: true