name: CyberCore
main: net.yungtechboy1.CyberCore.Main
version: "1.0.0"
api: ["1.0.0"]

author: Yungtechboy1
description: Core Plugin from Yungtech
commands:
  vote:
      description: vote
      usage: "/vote"
      permission: CyberTech.CyberCore.player
  reply:
      description: Quick Reply
      usage: "/reply <message>"
      permission: CyberTech.CyberCore.player
  r:
      description: Quick Reply
      usage: "/r <Message>"
      permission: CyberTech.CyberCore.player
  message:
      description: Private Message Player
      usage: "/message <Player> [Message]"
      permission: CyberTech.CyberCore.player
  msg:
      description: Private Message Player
      usage: "/msg <Player> [Message]"
      permission: CyberTech.CyberCore.player
  tpa:
      description: Accept Teleport
      usage: "/tpa"
      permission: CyberTech.CyberCore.player
  tpaccept:
      description: Accept Teleport
      usage: "/tpa"
      permission: CyberTech.CyberCore.player
  fix:
      description: Fix Item
      usage: "/fix"
      permission: CyberTech.CyberCore.player
  tpd:
      description: Deny Teleport
      usage: "/tpd"
      permission: CyberTech.CyberCore.player
  tpdeny:
      description: Deny Teleport
      usage: "/tpd"
      permission: CyberTech.CyberCore.player
  tpr:
      description: Request Teleport to player
      usage: "/tpr <Player>"
      permission: CyberTech.CyberCore.player
  cl:
      description: ClearInv
      usage: "/ci"
      permission: CyberTech.CyberCore.op
  top:
      description: TP To TOP
      usage: "/top"
      permission: CyberTech.CyberCore.player
  job:
      description: View All Jobs
      usage: "/job"
      permission: CyberTech.CyberCore.player
  tban:
      description: UnMutes player from chatting
      usage: "/tban"
      permission: CyberTech.CyberCore.player
  wild:
      description: Go To WILD!
      usage: "/wild"
      permission: CyberTech.CyberCore.player
  tcban:
      description: UnMutes player from chatting
      usage: "/tcban"
      permission: CyberTech.CyberCore.player
  tipban:
      description: UnMutes player from chatting
      usage: "/tipban"
      permission: CyberTech.CyberCore.player
  cban:
      description: UnMutes player from chatting
      usage: "/tipban"
      permission: CyberTech.CyberCore.player
  tipbanp:
      description: UnMutes player from chatting
      usage: "/tipbanp"
      permission: CyberTech.CyberCore.player
  tbanp:
      description: UnMutes player from chatting
      usage: "/tbanp"
      permission: CyberTech.CyberCore.player
  gmc:
      description: Mutting Local Chat
      usage: "/gmc"
      permission: CyberTech.CyberCore.op
  gms:
      description: Mutting Local Chat
      usage: "/gms"
      permission: CyberTech.CyberCore.op
permissions:
  CyberTech.CyberCore:
    description: "CyberChat Perms"
    children:
      CyberTech.CyberCore.op:
        default: op
      CyberTech.CyberCore.player:
        default: true